### ISSUE TITLE
<Say> verbs immediately play when dev phone rings

### ISSUE THREAD

**Issue by ayyrickay** [twilio-labs/dev-phone#146]
How to replicate: call the dev phone using a studio flow that uses a <Say> or <Play> verb. When you answer the call, it sounds like the audio has already started during the ring.

First reported by Joe Nash, as follows:

> Is it possible that a call TO a Dev Phone is technically getting answered somewhere before the call comes through to the browser? The reason I ask is outbound twilio calls containing just a single <Say> verb seem to end before Dev Phone rings, and if you add more content to those calls, they go through but have clearly already started.

**Comment by ayyrickay** [comment]
Does this involve `answerOnBridge`? [Documentation](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge)

Worst case scenario, we can brute force a fix by including a pause on this, but I think it may be related to multiple devices getting spun up by the webhook context.

**Comment by craigsdennis** [comment]
I think right here would do the trick testing wise: https://github.com/twilio-labs/dev-phone/blob/37505cbe43bbf641d7dd5bd534d075264615f727/packages/plugin-dev-phone/src/serverless/functions/incoming-call-handler.js#L6

**Comment by ayyrickay** [comment]
@craigsdennis is a genius, I think it worked. Testing now and if all is well then we can merge in and release a patch on Monday 👌
