### ISSUE TITLE
 twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/dev-phone/issues"

### ISSUE THREAD

**Issue by atgorvi** [twilio-labs/dev-phone#190]
I faced such an error, how can I fix it? 
![image](https://github.com/twilio-labs/dev-phone/assets/61602772/7ccd976c-ea29-4bf5-9a34-268dbe14d77f)

**Comment by ayyrickay** [comment]
Hi @atgorvi, it looks like you've got too many Functions Services on your account. I'm betting that if you go into the Twilio Console to look at them, you'll have several. Hopefully there are some that you can delete, and/or some way to consolidate the existing services you have.
